// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'tokens.dart';

// These functions are ignored because they are not marked as `pub`: `handle_update`, `stream_listen_task`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `InitializedEndpointInner`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<InitializedEndpoint>>
abstract class InitializedEndpoint implements RustOpaqueInterface {
  void cancelStream();

  static Future<InitializedEndpoint> create({required UserDefinedKey key}) =>
      RustLib.instance.api.crateApiEndpointInitializedEndpointCreate(key: key);

  Future<void> destroy();

  Future<PlatformInt64> execPing({required UserDefinedNode address});

  Stream<String> serveRemoteTcp({
    required int port,
    required UserDefinedNode address,
    String? namedPort,
  });
}
