[package]
name = "p2proxy-test-server"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
axum = { workspace = true }
tokio = { workspace = true }

[lints]
workspace = true
