[target.x86_64-unknown-linux-gnu]
image = "debian:bullseye-slim"
pre-build = [
    "apt-get update && apt-get -y upgrade && apt-get -y install build-essential libgtk-3-dev libglib2.0-dev"
]

[target.aarch64-unknown-linux-gnu]
image = "arm64v8/debian:bullseye-slim"
pre-build = [
    "apt-get update && apt-get -y upgrade && apt-get -y install build-essential libgtk-3-dev libglib2.0-dev"
]